name = "TestPackage"
uuid = "1db272ca-bb6a-4d7c-9426-e93aef723262"
authors = ["Lalit Chauhan"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
